env:
  browser: true
  es2021: true
extends: 'airbnb'
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules: {
  "no-param-reassign": ["error", {"props": true, "ignorePropertyModificationsFor": ['key'] }]

}
